CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Matches" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ExternalId" integer NOT NULL,
    "HomeTeam" text NOT NULL,
    "AwayTeam" text NOT NULL,
    "HomeScore" integer,
    "AwayScore" integer,
    "KickoffTime" timestamp with time zone NOT NULL,
    "Status" text NOT NULL,
    CONSTRAINT "PK_Matches" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "ClientId" text NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "Predictions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "MatchId" integer NOT NULL,
    "PredictedHome" integer NOT NULL,
    "PredictedAway" integer NOT NULL,
    "Points" integer NOT NULL,
    CONSTRAINT "PK_Predictions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Predictions_Matches_MatchId" FOREIGN KEY ("MatchId") REFERENCES "Matches" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Predictions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Predictions_MatchId" ON "Predictions" ("MatchId");

CREATE UNIQUE INDEX "IX_Predictions_UserId_MatchId" ON "Predictions" ("UserId", "MatchId");

CREATE UNIQUE INDEX "IX_Users_ClientId" ON "Users" ("ClientId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260405115334_Init', '10.0.5');

COMMIT;

