-- Etape 1 af multi-turnerings-planen (docs/PLAN-multi-turnering.md):
-- Competitions + CompetitionMembers oprettes, Matches får CompetitionId, og
-- den eksisterende VM 2026-data migreres ind som en afsluttet konkurrence.
-- Additiv migration — ingen RLS-ændringer her (de kommer i etape 3, sidst i
-- udrulningen), så den kørende klient påvirkes ikke.

create table "Competitions" (
  "Id" int generated by default as identity primary key,
  "Name" text not null,
  "CompetitionCode" text not null,            -- football-data.org-kode: WC, EC, PL, ...
  "DateFrom" date,                            -- API-hentevindue (null = hele turneringen)
  "DateTo" date,
  "Status" text not null default 'draft',
  "InviteToken" uuid not null default gen_random_uuid(),
  "RemindersEnabled" boolean not null default true,
  "InfoText" text,                            -- admin-redigerbar fritekst (Info-siden)
  "PrizesText" text,                          -- admin-redigerbar fritekst (Prizes-siden)
  "CreatedAt" timestamptz not null default now(),
  constraint "UQ_Competitions_InviteToken" unique ("InviteToken"),
  constraint "CK_Competitions_Status" check ("Status" in ('draft', 'active', 'finished', 'archived'))
);

create table "CompetitionMembers" (
  "Id" int generated by default as identity primary key,
  "CompetitionId" int not null references "Competitions"("Id") on delete cascade,
  "UserId" int not null references "Users"("Id") on delete cascade,
  "Role" text not null default 'player',
  "JoinedAt" timestamptz not null default now(),
  constraint "UQ_CompetitionMembers" unique ("CompetitionId", "UserId"),
  constraint "CK_CompetitionMembers_Role" check ("Role" in ('admin', 'player'))
);

create index "IX_CompetitionMembers_UserId" on "CompetitionMembers" ("UserId");

alter table "Matches"
  add column "CompetitionId" int references "Competitions"("Id") on delete cascade;

-- Backfill: VM 2026 ind som afsluttet konkurrence. Påmindelser slås fra —
-- turneringen er forbi, og reminder-jobbet skal ikke kigge på den igen.
with comp as (
  insert into "Competitions"
    ("Name", "CompetitionCode", "DateFrom", "DateTo", "Status", "RemindersEnabled")
  values
    ('VM Tips Kuponen 2026', 'WC', '2026-06-11', '2026-07-19', 'finished', false)
  returning "Id"
)
update "Matches" set "CompetitionId" = (select "Id" from comp);

alter table "Matches" alter column "CompetitionId" set not null;

-- ExternalId er kun unik inden for én konkurrence: to konkurrencer der følger
-- samme turnering ejer hver deres kamp-rækker med samme eksterne id.
alter table "Matches" drop constraint "UQ_Matches_ExternalId";
alter table "Matches"
  add constraint "UQ_Matches_CompetitionId_ExternalId" unique ("CompetitionId", "ExternalId");

-- Alle eksisterende spillere bliver medlemmer af VM-konkurrencen.
-- Kasper Arp (opslag via auth-email, ikke navn) bliver admin.
insert into "CompetitionMembers" ("CompetitionId", "UserId", "Role")
select
  c."Id",
  u."Id",
  case
    when u."AuthId" = (select id from auth.users where email = 'kasperarp@me.com')
      then 'admin'
    else 'player'
  end
from "Users" u
cross join "Competitions" c
where c."Name" = 'VM Tips Kuponen 2026';
